import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const cookieMaster = cookies();

  cookieMaster.getAll().map((cookie) => (
        console.log(cookie)
    ))
  return (
    <html lang="en">
      <body className={`${inter.className} h-screen w-full`}>
        {children}
      </body>
    </html>
  );
}
